export default userJson = {
  "avatar_url": "https://avatars1.githubusercontent.com/u/26186645?v=4",
  "bio": "Estudante de Sistemas de Informação na Universidade Federal de Sergipe Estudante de Sistemas de Informação na Universidade Federal de Sergipe Esstudante",
  "blog": "",
  "company": null,
  "created_at": "2017-03-04T15:08:52Z",
  "email": null,
  "events_url": "https://api.github.com/users/Eldeerick/events{/privacy}",
  "followers": 12,
  "followers_url": "https://api.github.com/users/Eldeerick/followers",
  "following": 16,
  "following_url": "https://api.github.com/users/Eldeerick/following{/other_user}",
  "gists_url": "https://api.github.com/users/Eldeerick/gists{/gist_id}",
  "gravatar_id": "",
  "hireable": true,
  "html_url": "https://github.com/Eldeerick",
  "id": 26186645,
  "location": "Brasil",
  "login": "Eldeerick",
  "name": "Erick Oliveira",
  "node_id": "MDQ6VXNlcjI2MTg2NjQ1",
  "organizations_url": "https://api.github.com/users/Eldeerick/orgs",
  "public_gists": 0,
  "public_repos": 12,
  "received_events_url": "https://api.github.com/users/Eldeerick/received_events",
  "repos_url": "https://api.github.com/users/Eldeerick/repos",
  "site_admin": false,
  "starred_url": "https://api.github.com/users/Eldeerick/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Eldeerick/subscriptions",
  "type": "User",
  "updated_at": "2020-04-23T21:12:00Z",
  "url": "https://api.github.com/users/Eldeerick",
}
